# ********************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) where distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# ********************************************************************************

header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Eclipse Foundation
    content: |
      ********************************************************************************
      Copyright (c) [year] Contributors to the [owner]

      See the NOTICE file(s) where distributed with this work for additional
      information regarding copyright ownership.
      
      This program and the accompanying materials are made
      available under the terms of the Apache Software License 2.0
      which is available at https://www.apache.org/licenses/LICENSE-2.0.
      
      SPDX-License-Identifier: Apache-2.0
      ********************************************************************************
  comment: on-failure

  paths-ignore:
    - 'LICENSE'
    - 'NOTICE'
    - '**/*.md'
    - '.gitignore'
    - '.dockerignore'
    - 'security/.gitignore'
    - 'security/mk-ca-bundle.pl'
    - 'security/certdata.txt'
    - 'sbin/*.template'
    - '.github/linters/.jscpd.json'
    - 'cyclonedx-lib/getDependencies'
    - 'makejdk-any-platform.1'
