.\" Manpage for makejdk-any-platform.sh
.TH "0.1.0" "Apache 2"
.SH NAME
makejdk.sh
.SH SYNOPSIS
"./makejdk-any-platform.sh --versions [versions] [options]"
.SH DESCRIPTION
The simplest way to build OpenJDK using our scripts is to run makejdk-any-platform.sh --version <jdk8u/jdk9> and have your user be in the Docker group on the machine (or prefix all of your Docker commands with sudo. This script can be used to create a Docker container that will be configured with all of the required dependencies and a base operating system in order to build OpenJDK.

.SH VERSIONS
.TP
.BR \jdk8u
https://github.com/AdoptOpenJDK/openjdk-jdk8u
.TP
.BR \jdk9
https://github.com/AdoptOpenJDK/openjdk-jdk9
.TP
.BR \jdk10
https://github.com/AdoptOpenJDK/openjdk-jdk10
.TP

.SH OPTIONS
.TP
.BR \-s ", " \-\-source " " \fI<path>\fR
specify the location for the source and dependencies to be cloned
.TP
.BR \-d ", " \-\-destination " " \fI<path>\fR
specify the location for the tarball (eg. /path/ or /path/here.tar.gz)
.TP
.BR \-r ", " \-\-repository " " \fI<repo>\fR
specify a custom repository (eg. username/openjdk-jdk8u)
.TP
.BR \-b ", " \-\-branch " " \fI<branch>\fR
specify a custom branch (eg. dev)
.TP
.BR \-k ", " \-\-keep
reuse docker container (prevents deleting)
.TP
.BR \-j ", " \-\-jtreg
run jtreg after building
.TP
.BR \-js ", " \-\-jtreg-subsets
select one or more jtreg tests to run
.TP
.BR \-sf ", " \-\-skip-freetype
skip building freetype
.BR \-nc ", " \-\-no-colour
disable colour output
.TP
.BR \-ftd ", " \-\-freetype-dir
specify the location of an existing FreeType library that can be used for the OpenJDK build process
.TP
.BR \-S ", " \-\-ssh
use ssh when cloning git
.TP
.BR \-dsgc ", " \-\-disable-shallow-git-clone
disable shallow cloning of git repo(s) using the --depth=1 CLI option
.TP
.BR \-bv ", " \-\-variant " " \fI<variant name>\fR
specify a custom build variant (eg. openj9)
.TP
