#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:16.04

LABEL maintainer="AdoptOpenJDK <adoption-discuss@openjdk.java.net>"

# Install required OS tools
RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get install -qq -y --no-install-recommends \
       autoconf \
       ccache \
       cpio \
       curl \
       file \
       g++-4.8 \
       gcc-4.8 \
       git \
       gnupg2 \
       libasound2-dev \
       libcups2-dev \
       libdwarf-dev \
       libelf-dev \
       libfontconfig1-dev \
       libfreetype6-dev \
       libnuma-dev \
       libx11-dev \
       libxext-dev \
       libxrandr-dev \
       libxrender-dev \
       libxt-dev \
       libxtst-dev \
       make \
       nasm \
       openjdk-8-jdk \
       pkg-config \
       ssh \
       unzip \
       wget \
       zip \
    && rm -rf /var/lib/apt/lists/*

# Make sure build uses 4.8
RUN ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc \
    && ln -sf /usr/bin/g++-4.8 /usr/bin/g++ \
    && ln -sf /usr/bin/g++-4.8 /usr/bin/c++

RUN mkdir -p /openjdk/target

# Extract AdoptOpenJDK12 for JDK_BOOT_DIR.
RUN wget 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk12?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jdk' -O jdk12.tar.gz
RUN mkdir -p /usr/lib/jvm/jdk12 && tar -xvf /jdk12.tar.gz -C /usr/lib/jvm/jdk12 --strip-components=1
RUN ln -sf /usr/lib/jvm/jdk12/bin/java /usr/bin/java
RUN ln -sf /usr/lib/jvm/jdk12/bin/javac /usr/bin/javac

COPY sbin /openjdk/sbin
COPY workspace/config /openjdk/config
COPY pipelines /openjdk/pipelines

# Create User "build"
ARG HostUID
ENV HostUID=$HostUID
RUN mkdir -p /openjdk/build
RUN useradd -u $HostUID -ms /bin/bash build
RUN chown -R build /openjdk/
USER build
WORKDIR /openjdk/build/

ARG OPENJDK_CORE_VERSION
ENV OPENJDK_CORE_VERSION=$OPENJDK_CORE_VERSION
ENV JDK_PATH=jdk
ENV JDK8_BOOT_DIR=/usr/lib/jvm/java-8-openjdk-amd64

