/*
 * *******************************************************************************
 * Copyright (c) 2024, 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Apache Software License 2.0
 * which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: Apache-2.0
 * ********************************************************************************
 */

// Some portions generated by IBM Bob

package temurin.sbom;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.cyclonedx.exception.GeneratorException;
import org.cyclonedx.generators.json.BomJsonGenerator;
import org.cyclonedx.generators.xml.BomXmlGenerator;
import org.cyclonedx.model.AttachmentText;
import org.cyclonedx.model.Bom;
import org.cyclonedx.model.Component;
import org.cyclonedx.model.ExternalReference;
import org.cyclonedx.model.Hash;
import org.cyclonedx.model.Property;
import org.cyclonedx.model.OrganizationalEntity;
import org.cyclonedx.model.attestation.Declarations;
import org.cyclonedx.model.attestation.Assessor;
import org.cyclonedx.model.attestation.Attestation;
import org.cyclonedx.model.attestation.AttestationMap;
import org.cyclonedx.model.attestation.Claim;
import org.cyclonedx.model.attestation.affirmation.Affirmation;
import org.cyclonedx.model.attestation.evidence.Contents;
import org.cyclonedx.model.attestation.evidence.Data;
import org.cyclonedx.model.attestation.evidence.Evidence;
import org.cyclonedx.model.attestation.Targets;
import org.cyclonedx.parsers.JsonParser;
import org.cyclonedx.parsers.XmlParser;
import org.cyclonedx.Version;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.List;
import java.util.LinkedList;
import java.util.UUID;

/**
 * Command line tool to construct a CycloneDX CDXA.
 */
public final class TemurinGenCDXA {

    private static boolean verbose = false;
    private static boolean useJson = false;

    // Constants for evidence fields
    private static final String EVIDENCE_PROPERTY_NAME = "VERIFICATION_LOG";
    private static final String EVIDENCE_DATA_NAME = "log";
    private static final String EVIDENCE_CONTENT_TYPE = "text/plain";

    // Constants for component properties
    private static final String COMPONENT_IMAGE_TYPE = "jdk";
    private static final String COMPONENT_JVM_IMPL = "hotspot";

    // Valid predicates
    enum CDXAPredicate {
                           VERIFIED_REPRODUCIBLE_BUILD
                       };

    /**
     * Helper class to return multiple values from evidence parsing.
     */
    static class EvidenceData {
        private final String version;
        private final String arch;
        private final String os;
        private final String hash;

        EvidenceData(final String versionParam, final String archParam, final String osParam, final String hashParam) {
            this.version = versionParam;
            this.arch = archParam;
            this.os = osParam;
            this.hash = hashParam;
        }

        public String getVersion() {
            return version;
        }

        public String getArch() {
            return arch;
        }

        public String getOs() {
            return os;
        }

        public String getHash() {
            return hash;
        }
    }

    /**
     * Helper class to return CDXA creation result with extracted metadata.
     */
    static class CdxaResult {
        private final Bom bom;
        private final String version;
        private final String arch;
        private final String os;

        CdxaResult(final Bom bomParam, final String versionParam, final String archParam, final String osParam) {
            this.bom = bomParam;
            this.version = versionParam;
            this.arch = archParam;
            this.os = osParam;
        }

        public Bom getBom() {
            return bom;
        }

        public String getVersion() {
            return version;
        }

        public String getArch() {
            return arch;
        }

        public String getOs() {
            return os;
        }
    }

    private TemurinGenCDXA() {
    }

    /**
     * Main entry.
     * @param args Arguments for operation.
     */
    public static void main(final String[] args) {
        String cmd = "";
        String attestingOrgName = null;
        String predicate = null;
        String affirmationStmt = null;
        String affirmationWebsite = null;
        String evidenceText = null;
        String cdxaOutputFolder = "."; // Default to current directory
        boolean thirdParty = true;
        useJson = false; // Default to XML

        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--json")) {
                useJson = true;
            } else if (args[i].equals("--xml")) {
                useJson = false;
            } else if (args[i].equals("--attesting-org-name")) {
                attestingOrgName = getOptionValue(args, i, "--attesting-org-name");
                i++; // Skip the value we just consumed
            } else if (args[i].equals("--predicate")) {
                predicate = getOptionValue(args, i, "--predicate");
                i++;
            } else if (args[i].equals("--affirmation-stmt")) {
                affirmationStmt = getOptionValue(args, i, "--affirmation-stmt");
                i++;
            } else if (args[i].equals("--evidence")) {
                String evidenceFilePath = getOptionValue(args, i, "--evidence");
                evidenceText = readEvidenceFile(evidenceFilePath);
                i++;
            } else if (args[i].equals("--cdxa-output-folder")) {
                cdxaOutputFolder = getOptionValue(args, i, "--cdxa-output-folder");
                i++;
            // CycloneDX core java XML generation bug missing Signatories ExternalReference website: https://github.com/CycloneDX/cyclonedx-core-java/issues/812
            // Add back in when resuled upstream
            //} else if (args[i].equals("--affirmation-website")) {
            //    affirmationWebsite = getOptionValue(args, i, "--affirmation-website");
            //    i++;
            } else if (args[i].equals("--not-third-party")) {
                thirdParty = false;
            } else if (args[i].equals("--createNewCDXA")) {
                cmd = "createCDXA";
            } else if (args[i].equals("--verbose")) {
                verbose = true;
            }
        }

        try {
          switch (cmd) {
            case "createCDXA":  // Create a new CDXA json/xml file
                // Validate output folder
                File outputFolder = new File(cdxaOutputFolder);
                if (!outputFolder.exists()) {
                    System.out.println("ERROR: --cdxa-output-folder '" + cdxaOutputFolder + "' does not exist");
                    printUsage();
                    System.exit(1);
                }
                if (!outputFolder.isDirectory()) {
                    System.out.println("ERROR: --cdxa-output-folder '" + cdxaOutputFolder + "' is not a directory");
                    printUsage();
                    System.exit(1);
                }
                if (!outputFolder.canWrite()) {
                    System.out.println("ERROR: --cdxa-output-folder '" + cdxaOutputFolder + "' is not writable");
                    printUsage();
                    System.exit(1);
                }

                CdxaResult result = createCdxa(attestingOrgName, predicate, affirmationStmt, affirmationWebsite, evidenceText, thirdParty);
                if (result != null && result.getBom() != null) {
                    // Derive fileName from extracted values
                    String fileName = deriveFileName(result.getVersion(), result.getArch(), result.getOs(), attestingOrgName);
                    // Prepend output folder to filename
                    String fullPath = cdxaOutputFolder + File.separator + fileName;
                    writeFile(result.getBom(), fullPath);
                    if (verbose) {
                        System.out.println("CDXA file written to: " + fullPath);
                    }
                } else {
                    System.exit(1);
                }
                break;

            default:
                // Echo input command:
                for (int i = 0; i < args.length; i++) {
                    System.out.print(args[i] + " ");
                }
                System.out.println("\nERROR: Please enter a valid command.");
                printUsage();
                System.exit(1);
          }
        } catch (Exception e) {
            // Echo input command:
            for (int i = 0; i < args.length; i++) {
                System.out.print(args[i] + " ");
            }
            System.out.println("\nERROR: Exception: " + e);
            printUsage();
            System.exit(1);
        }
    }

    /**
     * Validates and reads the contents of an evidence file.
     * Checks that the file exists, is a file, and is readable.
     * Prints error message and usage, then exits on failure.
     *
     * @param evidenceFilePath The path to the evidence file
     * @return The contents of the evidence file as a string
     */
    private static String readEvidenceFile(final String evidenceFilePath) {
        File evFile = new File(evidenceFilePath);

        if (!evFile.exists()) {
            System.out.println("ERROR: --evidence file '" + evidenceFilePath + "' does not exist");
            printUsage();
            System.exit(1);
        }
        if (!evFile.isFile()) {
            System.out.println("ERROR: --evidence '" + evidenceFilePath + "' is not a file");
            printUsage();
            System.exit(1);
        }
        if (!evFile.canRead()) {
            System.out.println("ERROR: --evidence file '" + evidenceFilePath + "' is not readable");
            printUsage();
            System.exit(1);
        }

        try {
            String contents = readFileContents(evidenceFilePath);
            if (verbose) {
                System.out.println("Read evidence from file: " + evidenceFilePath
                                 + " (" + contents.length() + " characters)");
            }
            return contents;
        } catch (IOException e) {
            System.out.println("ERROR: Failed to read evidence file '" + evidenceFilePath
                             + "': " + e.getMessage());
            printUsage();
            System.exit(1);
            return null; // Never reached, but needed for compilation
        }
    }
    /**
     * Parses evidence text to extract and validate build information.
     * Expected format includes lines like:
     * Eclipse Temurin version: jdk-21.0.11+9
     *                    arch: aarch64
     *                      os: linux
     *                  sha256: 51111aa918a1b3e4f59e1ce3179f1a17345a7024825ce98d634820c38d9a46a2
     *
     * @param evidenceText The evidence text content
     * @return EvidenceData containing version, arch, os, and hash, or null if parsing/validation fails
     */
    private static EvidenceData parseAndValidateEvidence(final String evidenceText) {
        if (evidenceText == null || evidenceText.trim().isEmpty()) {
            System.out.println("ERROR: Evidence text is empty");
            printUsage();
            return null;
        }

        // Patterns to extract values from evidence text
        Pattern versionPattern = Pattern.compile("Eclipse Temurin version:\\s*([^\\s]+)");
        Pattern archPattern = Pattern.compile("arch:\\s*([^\\s]+)");
        Pattern osPattern = Pattern.compile("os:\\s*([^\\s]+)");
        Pattern sha256Pattern = Pattern.compile("sha256:\\s*([0-9a-fA-F]{64})");
        Pattern reproduciblePattern = Pattern.compile("ReproduciblePercent\\s*=\\s*100\\s*%");

        Matcher versionMatcher = versionPattern.matcher(evidenceText);
        Matcher archMatcher = archPattern.matcher(evidenceText);
        Matcher osMatcher = osPattern.matcher(evidenceText);
        Matcher sha256Matcher = sha256Pattern.matcher(evidenceText);
        Matcher reproducibleMatcher = reproduciblePattern.matcher(evidenceText);

        // Extract values
        String extractedVersion = versionMatcher.find() ? versionMatcher.group(1) : null;
        String extractedArch = archMatcher.find() ? archMatcher.group(1) : null;
        String extractedOs = osMatcher.find() ? osMatcher.group(1) : null;
        String extractedSha256 = sha256Matcher.find() ? sha256Matcher.group(1) : null;
        boolean hasReproducible100 = reproducibleMatcher.find();

        // Validate extracted values exist
        boolean hasErrors = false;
        if (extractedVersion == null) {
            System.out.println("ERROR: Could not find 'Eclipse Temurin version:' in evidence text");
            hasErrors = true;
        }
        if (extractedArch == null) {
            System.out.println("ERROR: Could not find 'arch:' in evidence text");
            hasErrors = true;
        }
        if (extractedOs == null) {
            System.out.println("ERROR: Could not find 'os:' in evidence text");
            hasErrors = true;
        }
        if (extractedSha256 == null) {
            System.out.println("ERROR: Could not find 'sha256:' (64-character hex string) in evidence text");
            hasErrors = true;
        }
        if (!hasReproducible100) {
            System.out.println("ERROR: Evidence does not indicate a successful 100% reproducible verification");
            System.out.println("       Expected to find 'ReproduciblePercent = 100 %' in evidence text");
            hasErrors = true;
        }

        if (hasErrors) {
            printUsage();
            return null;
        }

        if (verbose) {
            System.out.println("Extracted from evidence:");
            System.out.println("  Version: " + extractedVersion);
            System.out.println("  Arch: " + extractedArch);
            System.out.println("  OS: " + extractedOs);
            System.out.println("  SHA-256: " + extractedSha256);
        }

        // Validate extracted values meet format requirements
        if (!validateEvidenceParameters(extractedVersion, extractedOs, extractedArch)) {
            printUsage();
            return null;
        }

        // Validate hash against Adoptium API
        if (!validateHashWithAdoptium(extractedSha256, extractedVersion, extractedOs, extractedArch)) {
            return null;
        }

        return new EvidenceData(extractedVersion, extractedArch, extractedOs, extractedSha256);
    }


    /**
     * Queries the Adoptium API to get the official SHA-256 hash for a JDK build.
     * API URL format: https://api.adoptium.net/v3/checksum/version/{version}/{os}/{arch}/jdk/hotspot/normal/eclipse
     *
     * @param version The JDK version (e.g., jdk-21.0.5+11)
     * @param os The operating system (linux, windows, mac)
     * @param arch The architecture (x64, aarch64, s390x, ppc64le)
     * @return The SHA-256 hash from Adoptium API, or null if query fails
     */
    private static String queryAdoptiumHash(final String version, final String os, final String arch) {
        String apiUrl = String.format(
            "https://api.adoptium.net/v3/checksum/version/%s/%s/%s/jdk/hotspot/normal/eclipse",
            version, os, arch
        );

        if (verbose) {
            System.out.println("Querying Adoptium API: " + apiUrl);
        }

        try {
            URL url = new URL(apiUrl);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("User-Agent", "TemurinGenCDXA/1.0");
            conn.setConnectTimeout(10000); // 10 seconds
            conn.setReadTimeout(10000);

            int responseCode = conn.getResponseCode();
            if (responseCode != 200) {
                System.out.println("ERROR: Adoptium API returned status code " + responseCode + " for URL: " + apiUrl);
                return null;
            }

            BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            // Response format is: "hash  filename"
            // Extract just the hash (first field before space)
            String responseText = response.toString().trim();
            String[] parts = responseText.split("\\s+");
            if (parts.length > 0) {
                String adoptiumHash = parts[0].trim();
                if (verbose) {
                    System.out.println("Adoptium API hash: " + adoptiumHash);
                }
                return adoptiumHash;
            }

            System.out.println("ERROR: Could not parse Adoptium API response: " + responseText);
            return null;

        } catch (IOException e) {
            System.out.println("ERROR: Failed to query Adoptium API: " + e.getMessage());
            return null;
        }
    }

    /**
     * Validates that the SHA-256 hash from evidence matches the official Adoptium API hash.
     *
     * @param evidenceHash The SHA-256 hash extracted from evidence
     * @param version The JDK version
     * @param os The operating system
     * @param arch The architecture
     * @return true if validation passes, false if hashes don't match or API query fails
     */
    private static boolean validateHashWithAdoptium(final String evidenceHash,
                                                     final String version,
                                                     final String os,
                                                     final String arch) {
        String adoptiumHash = queryAdoptiumHash(version, os, arch);

        if (adoptiumHash == null) {
            System.out.println("ERROR: Could not verify evidence hash against Adoptium API");
            printUsage();
            return false;
        }

        if (!evidenceHash.equalsIgnoreCase(adoptiumHash)) {
            System.out.println("ERROR: Evidence SHA-256 '" + evidenceHash
                             + "' does not match Adoptium API hash '" + adoptiumHash + "'");
            printUsage();
            return false;
        }

        if (verbose) {
            System.out.println("[OK] Evidence SHA-256 matches Adoptium API hash");
        }

        return true;
    }

    /**
     * Validates that the next argument exists, is not another option (doesn't start with "--"),
     * and returns the trimmed value. Prints error message and usage, then exits on failure.
     *
     * @param args The command-line arguments array
     * @param currentIndex The current index in the args array (the option itself)
     * @param optionName The name of the option (for error messages)
     * @return The trimmed option value, or exits the program if invalid
     */
    private static String getOptionValue(final String[] args, final int currentIndex, final String optionName) {
        // Check if there's a next argument
        if (currentIndex + 1 >= args.length) {
            System.out.println("ERROR: Option " + optionName + " requires a value");
            printUsage();
            System.exit(1);
        }

        String value = args[currentIndex + 1];

        // Check if the value is actually another option
        if (value.startsWith("--")) {
            System.out.println("ERROR: Option " + optionName + " requires a value, but found another option: " + value);
            printUsage();
            System.exit(1);
        }

        return value.trim();
    }

    static CdxaResult createCdxa(final String attestingOrgName, final String predicate,
                                 final String affirmationStmt, final String affirmationWebsite,
                                 final String evidenceText, final boolean thirdParty) {
        // Validate all inputs
        if (!validateCdxaInputs(attestingOrgName, predicate, affirmationStmt, evidenceText)) {
            printUsage();
            return null;
        }

        // Parse evidence text to extract version, arch, os, and SHA-256 hash
        EvidenceData evidenceData = parseAndValidateEvidence(evidenceText);
        if (evidenceData == null) {
            return null;
        }

        // Extract values from evidence
        String targetRelease = evidenceData.getVersion();
        String targetArch = evidenceData.getArch();
        String targetOs = evidenceData.getOs();
        String targetHash = evidenceData.getHash();

        // Derive CDXA values from extracted evidence
        String targetName = deriveTargetName(targetRelease, targetArch, targetOs);
        String targetVersion = targetRelease;
        String targetUrl = deriveTargetUrl(targetRelease, targetOs, targetArch);

        // Create BOM reference IDs
        final String targetJdkBomRef  = "target-jdk-1";
        final String assessorBomRef   = "assessor-1";
        final String claimBomRef      = "claim-1";
        final String evidenceBomRef   = "evidence-1";

        // Build CDXA components
        Declarations declarations = new Declarations();
        Component targetJDK = createTargetComponent(targetName, targetVersion, targetUrl, targetHash,
                                                     targetJdkBomRef, targetArch, targetOs);
        Targets targets = new Targets();
        List<Component> components = new LinkedList<Component>();
        components.add(targetJDK);
        targets.setComponents(components);
        declarations.setTargets(targets);

        Assessor assessor = createAssessor(attestingOrgName, assessorBomRef, thirdParty);
        List<Assessor> assessors = new LinkedList<Assessor>();
        assessors.add(assessor);
        declarations.setAssessors(assessors);

        Claim claim = createClaim(predicate, targetJDK.getBomRef(), claimBomRef, evidenceBomRef);
        List<Claim> claims = new LinkedList<Claim>();
        claims.add(claim);
        declarations.setClaims(claims);

        Affirmation affirmation = new Affirmation();
        affirmation.setStatement(affirmationStmt);

        /*
         * CycloneDX core java XML generation bug missing Signatories ExternalReference website: https://github.com/CycloneDX/cyclonedx-core-java/issues/812
         * Add back in when resolved upstream
        Signatory      signatory    = new Signatory();
        OrganizationalEntity org = new OrganizationalEntity();
        org.setName(attestingOrgName);
        signatory.setOrganization(org);
        ExternalReference orgExtRef = new ExternalReference();
        orgExtRef.setUrl(affirmationWebsite);
        orgExtRef.setType(ExternalReference.Type.WEBSITE);
        signatory.setExternalReference(orgExtRef);
        List<Signatory> signatories = new LinkedList<Signatory>();
        signatories.add(signatory);
        affirmation.setSignatories(signatories);
        */

        declarations.setAffirmation(affirmation);

        Evidence evidence = createEvidence(evidenceText, evidenceBomRef);
        List<Evidence> evidenceList = new LinkedList<Evidence>();
        evidenceList.add(evidence);
        declarations.setEvidence(evidenceList);

        Attestation attestation = createAttestation(assessor.getBomRef(), claim.getBomRef());
        List<Attestation> attestations = new LinkedList<Attestation>();
        attestations.add(attestation);
        declarations.setAttestations(attestations);

        // Create CDXA Bom
        Bom cdxa = new Bom();
        cdxa.setSerialNumber("urn:uuid:" + UUID.randomUUID());
        cdxa.setDeclarations(declarations);

        return new CdxaResult(cdxa, targetRelease, targetArch, targetOs);
    }

    /**
     * Validates all CDXA input parameters.
     *
     * @param attestingOrgName The name of the organization making the attestation
     * @param predicate The predicate type for the claim
     * @param affirmationStmt The affirmation statement
     * @param evidenceText The evidence text content
     * @return true if all inputs are valid, false otherwise
     */
    private static boolean validateCdxaInputs(final String attestingOrgName, final String predicate,
                                              final String affirmationStmt, final String evidenceText) {
        boolean validInput = true;

        if (attestingOrgName == null) {
            System.out.println("ERROR: --attesting-org-name not specified");
            validInput = false;
        }
        if (predicate == null) {
            System.out.println("ERROR: --predicate not specified");
            validInput = false;
        } else {
            boolean validPred = false;
            for (CDXAPredicate validPredicate : CDXAPredicate.values()) {
                if (validPredicate.name().equals(predicate)) {
                    validPred = true;
                    break;
                }
            }
            if (!validPred) {
                System.out.println("ERROR: --predicate " + predicate + " not a valid value");
                validInput = false;
            }
        }
        if (affirmationStmt == null) {
            System.out.println("ERROR: --affirmation-stmt not specified");
            validInput = false;
        }
        if (evidenceText == null) {
            System.out.println("ERROR: --evidence not specified");
            validInput = false;
        } else if (evidenceText.trim().isEmpty()) {
            System.out.println("ERROR: --evidence cannot be empty");
            validInput = false;
        }

        return validInput;
    }

    /**
     * Creates the target JDK component with all properties.
     *
     * @param targetName The name of the target JDK
     * @param targetVersion The version of the target JDK
     * @param targetUrl The URL to download the target JDK
     * @param targetHash The SHA-256 hash of the target JDK
     * @param bomRef The BOM reference identifier
     * @param targetArch The target architecture
     * @param targetOs The target operating system
     * @return The configured Component object representing the target JDK
     */
    private static Component createTargetComponent(final String targetName, final String targetVersion,
                                                   final String targetUrl, final String targetHash,
                                                   final String bomRef, final String targetArch,
                                                   final String targetOs) {
        // External reference to the target JDK
        ExternalReference extRef = new ExternalReference();
        Hash hash1 = new Hash(Hash.Algorithm.SHA_256, targetHash);
        extRef.addHash(hash1);
        extRef.setUrl(targetUrl);
        extRef.setType(ExternalReference.Type.DISTRIBUTION);

        // Target JDK Component
        Component targetJDK = new Component();
        targetJDK.setType(Component.Type.APPLICATION);
        targetJDK.setName(targetName);
        targetJDK.setVersion(targetVersion);
        targetJDK.addExternalReference(extRef);
        targetJDK.setBomRef(bomRef);

        // Property for "platform" = {arch}_{os}
        Property property = new Property();
        property.setName("platform");
        property.setValue(targetArch + "_" + targetOs);
        targetJDK.addProperty(property);

        // Property for "imageType"
        Property imageTypeProperty = new Property();
        imageTypeProperty.setName("imageType");
        imageTypeProperty.setValue(COMPONENT_IMAGE_TYPE);
        targetJDK.addProperty(imageTypeProperty);

        // Property for "jvmImpl"
        Property jvmImplProperty = new Property();
        jvmImplProperty.setName("jvmImpl");
        jvmImplProperty.setValue(COMPONENT_JVM_IMPL);
        targetJDK.addProperty(jvmImplProperty);

        return targetJDK;
    }

    /**
     * Creates the assessor component.
     *
     * @param attestingOrgName The name of the attesting organization
     * @param bomRef The BOM reference identifier
     * @param thirdParty Whether the assessor is a third party
     * @return The configured Assessor object
     */
    private static Assessor createAssessor(final String attestingOrgName, final String bomRef,
                                          final boolean thirdParty) {
        Assessor assessor = new Assessor();
        assessor.setThirdParty(thirdParty);
        OrganizationalEntity org = new OrganizationalEntity();
        org.setName(attestingOrgName);
        assessor.setOrganization(org);
        assessor.setBomRef(bomRef);
        return assessor;
    }

    /**
     * Creates the claim component.
     *
     * @param predicate The predicate type for the claim
     * @param targetBomRef The BOM reference of the target component
     * @param claimBomRef The BOM reference for this claim
     * @param evidenceBomRef The BOM reference of the supporting evidence
     * @return The configured Claim object
     */
    private static Claim createClaim(final String predicate, final String targetBomRef,
                                    final String claimBomRef, final String evidenceBomRef) {
        Claim claim = new Claim();
        claim.setPredicate(predicate);
        claim.setTarget(targetBomRef);
        claim.setBomRef(claimBomRef);

        // Add evidence reference to claim
        List<String> evidenceRefs = new LinkedList<String>();
        evidenceRefs.add(evidenceBomRef);
        claim.setEvidence(evidenceRefs);

        return claim;
    }

    /**
     * Creates the evidence component.
     *
     * @param evidenceText The text content of the evidence
     * @param bomRef The BOM reference identifier
     * @return The configured Evidence object
     */
    private static Evidence createEvidence(final String evidenceText, final String bomRef) {
        Evidence evidence = new Evidence();
        evidence.setBomRef(bomRef);
        evidence.setPropertyName(EVIDENCE_PROPERTY_NAME);

        // Create Data object
        Data data = new Data();
        data.setName(EVIDENCE_DATA_NAME);

        // Create Contents with AttachmentText
        Contents contents = new Contents();
        AttachmentText attachment = new AttachmentText();
        attachment.setContentType(EVIDENCE_CONTENT_TYPE);
        attachment.setText(evidenceText);
        contents.setAttachment(attachment);
        data.setContents(contents);

        // Add data to evidence
        List<Data> dataList = new LinkedList<Data>();
        dataList.add(data);
        evidence.setData(dataList);

        return evidence;
    }

    /**
     * Creates the attestation component.
     *
     * @param assessorBomRef The BOM reference of the assessor
     * @param claimBomRef The BOM reference of the claim
     * @return The configured Attestation object
     */
    private static Attestation createAttestation(final String assessorBomRef, final String claimBomRef) {
        Attestation attestation = new Attestation();
        attestation.setSummary("Eclipse Temurin CycloneDX Attestation");
        attestation.setAssessor(assessorBomRef);

        AttestationMap attestationMap = new AttestationMap();
        List<String> claimsList = new LinkedList<String>();
        claimsList.add(claimBomRef);
        attestationMap.setClaims(claimsList);

        List<AttestationMap> attestationMaps = new LinkedList<AttestationMap>();
        attestationMaps.add(attestationMap);
        attestation.setMap(attestationMaps);

        return attestation;
    }

    /**
     * Prints usage information for the command-line tool.
     */
    static void printUsage() {
        System.out.println("\nUsage: TemurinGenCDXA --createNewCDXA [OPTIONS]");
        System.out.println("\nRequired Options:");
        System.out.println("  --attesting-org-name <name>    Organization name making the attestation");
        System.out.println("  --predicate <predicate>        Predicate type (e.g., VERIFIED_REPRODUCIBLE_BUILD)");
        System.out.println("  --affirmation-stmt <stmt>      Affirmation statement");
        System.out.println("  --evidence <file>              Path to file containing verification evidence log text");
        System.out.println("                                 (must include version, arch, os, and sha256 fields)");
        System.out.println("\nOptional Options:");
        System.out.println("  --cdxa-output-folder <path>    Output folder for CDXA file (default: current directory)");
        //System.out.println("  --affirmation-website <url>    Organization website"); // Removed until bug fixed: https://github.com/CycloneDX/cyclonedx-core-java/issues/812
        System.out.println("  --json                         Generate JSON output (default: XML)");
        System.out.println("  --xml                          Generate XML output");
        System.out.println("  --not-third-party              Mark assessor as not third-party");
        System.out.println("  --verbose                      Enable verbose output");
        System.out.println("\nExamples:");
        System.out.println("  TemurinGenCDXA --createNewCDXA \\");
        System.out.println("    --attesting-org-name \"Acme Inc\" \\");
        System.out.println("    --predicate VERIFIED_REPRODUCIBLE_BUILD \\");
        System.out.println("    --affirmation-stmt \"Build verified as reproducible\" \\");
        System.out.println("    --evidence /path/to/evidence.txt \\");
        System.out.println("    --cdxa-output-folder /output/cdxa \\");
        //System.out.println("    --affirmation-website \"https://acme.inc.com\"");
        System.out.println("    --xml");
        System.out.println("\nOutput:");
        System.out.println("  Generated filename format: {release}_{arch}_{os}_{org}.{xml|json}");
        System.out.println("  Example: jdk_21_0_1_12_x64_linux_AcmeInc.xml");
        System.out.println("\nNote:");
        System.out.println("  - Version, arch, os, and SHA-256 hash are extracted from the evidence file");
        System.out.println("  - SHA-256 hash is validated against the Adoptium API");
    }

    /**
     * Validates evidence parameters according to Temurin CDXA requirements.
     *
     * @param version The JDK version extracted from evidence (jdk-M+B or jdk-M.0.U+B format)
     * @param os The OS extracted from evidence (linux, windows, mac)
     * @param arch The architecture extracted from evidence (x64, aarch64, s390x, ppc64le)
     * @return true if valid, false otherwise
     */
    static boolean validateEvidenceParameters(final String version, final String os, final String arch) {
        boolean valid = true;

        // Validate version format: jdk-M+B or jdk-M.0.U+B
        Pattern releasePattern = Pattern.compile("^jdk-([0-9]+)(\\.[0-9]+\\.[0-9]+)?\\+([0-9]+)$");
        Matcher releaseMatcher = releasePattern.matcher(version);
        if (!releaseMatcher.matches()) {
            System.out.println("ERROR: Evidence version '" + version + "' is not in valid format: jdk-M+B or jdk-M.0.U+B");
            valid = false;
        }

        // Validate os
        if (!os.equals("linux") && !os.equals("windows") && !os.equals("mac")) {
            System.out.println("ERROR: Evidence os '" + os + "' must be one of: linux, windows, mac");
            valid = false;
        }

        // Validate arch
        if (!arch.equals("x64") && !arch.equals("aarch64")
            && !arch.equals("s390x") && !arch.equals("ppc64le")) {
            System.out.println("ERROR: Evidence arch '" + arch + "' must be one of: x64, aarch64, s390x, ppc64le");
            valid = false;
        }

        return valid;
    }

    /**
     * Derives the target name from release, arch, and OS.
     * Format: "Temurin {targetRelease} {targetArch}_{targetOs}"
     *
     * @param targetRelease The target release
     * @param targetArch The target architecture
     * @param targetOs The target OS
     * @return The derived target name
     */
    static String deriveTargetName(final String targetRelease, final String targetArch, final String targetOs) {
        return "Temurin " + targetRelease + " " + targetArch + "_" + targetOs;
    }

    /**
     * Derives the target URL from release, OS, and arch.
     * Format: "https://api.adoptium.net/v3/binary/version/{targetRelease}/{targetOs}/{targetArch}/jdk/hotspot/normal/eclipse"
     *
     * @param targetRelease The target release
     * @param targetOs The target OS
     * @param targetArch The target architecture
     * @return The derived target URL
     */
    static String deriveTargetUrl(final String targetRelease, final String targetOs, final String targetArch) {
        return "https://api.adoptium.net/v3/binary/version/" + targetRelease + "/" + targetOs + "/" + targetArch + "/jdk/hotspot/normal/eclipse";
    }

    /**
     * Derives the file name from release, arch, OS, and attesting org.
     * Format: "{targetRelease with [-\.\+] converted to [_]}_{targetArch}_{targetOs}_{attestingOrgName}.{xml|json}"
     *
     * @param targetRelease The target release
     * @param targetArch The target architecture
     * @param targetOs The target OS
     * @param attestingOrgName The attesting organization name
     * @return The derived file name
     */
    static String deriveFileName(final String targetRelease, final String targetArch,
                                 final String targetOs, final String attestingOrgName) {
        // Convert all [-\.\+] to [_] in targetRelease
        String releaseFormatted = targetRelease.replaceAll("[-\\.\\+]", "_");
        // Remove all non-alphanumeric characters from attestingOrgName for valid filename
        String orgFormatted = attestingOrgName.replaceAll("[^a-zA-Z0-9]", "");
        String extension = useJson ? "json" : "xml";
        return releaseFormatted + "_" + targetArch + "_" + targetOs + "_" + orgFormatted + "." + extension;
    }

    static String generateBomJson(final Bom bom) throws GeneratorException {
        // Use schema v16: https://cyclonedx.org/schema/bom-1.6.schema.json
        BomJsonGenerator bomGen = new BomJsonGenerator(bom, Version.VERSION_16);
        String json = bomGen.toJsonString();
        return json;
    }

    static String generateBomXml(final Bom bom) throws GeneratorException {
        BomXmlGenerator bomGen = new BomXmlGenerator(bom, Version.VERSION_16);
        String xml = bomGen.toXmlString();
        return xml;
    }

    // Writes the BOM object to the specified type of file
    static void writeFile(final Bom bom, final String fileName) {
        if (useJson) {
            writeJSONfile(bom, fileName);
        } else {
            writeXMLfile(bom, fileName);
        }
    }

    // Writes the BOM object to the specified JSON file.
    static void writeJSONfile(final Bom bom, final String fileName) {
        FileWriter file;
        try {
            String json = generateBomJson(bom);

            file = new FileWriter(fileName);
            file.write(json);
            file.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    // Writes the BOM object to the specified XML file.
    static void writeXMLfile(final Bom bom, final String fileName) {
        FileWriter file;
        try {
            String xml = generateBomXml(bom);

            file = new FileWriter(fileName);
            file.write(xml);
            file.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    // Returns a parsed BOM object from the specified file.
    static Bom readJSONfile(final String fileName) {
        Bom bom = null;
        try {
            FileReader reader = new FileReader(fileName);
            JsonParser parser = new JsonParser();
            bom = parser.parse(reader);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        } finally {
           return bom;
        }
    }

    // Returns a parsed BOM object from the specified file.
    static Bom readXMLfile(final String fileName) {
        Bom bom = null;
        try {
            FileReader reader = new FileReader(fileName);
            XmlParser parser = new XmlParser();
            bom = parser.parse(reader);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        } finally {
           return bom;
        }
    }

    /**
     * Reads the entire contents of a text file.
     *
     * @param filePath The path to the file to read
     * @return The contents of the file as a string
     * @throws IOException If an I/O error occurs
     */
    static String readFileContents(final String filePath) throws IOException {
        StringBuilder content = new StringBuilder();
        try (FileReader reader = new FileReader(filePath)) {
            char[] buffer = new char[8192];
            int charsRead;
            while ((charsRead = reader.read(buffer)) != -1) {
                content.append(buffer, 0, charsRead);
            }
        }
        return content.toString();
    }

}
