/*
 n********************************************************************************
 * Copyright (c) 2024, 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Apache Software License 2.0
 * which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: Apache-2.0
 * ********************************************************************************
 */

// Some portions generated by IBM Bob

package temurin.sbom;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.cyclonedx.exception.GeneratorException;
import org.cyclonedx.generators.json.BomJsonGenerator;
import org.cyclonedx.generators.xml.BomXmlGenerator;
import org.cyclonedx.model.AttachmentText;
import org.cyclonedx.model.Bom;
import org.cyclonedx.model.Component;
import org.cyclonedx.model.ExternalReference;
import org.cyclonedx.model.Hash;
import org.cyclonedx.model.Property;
import org.cyclonedx.model.OrganizationalEntity;
import org.cyclonedx.model.attestation.Declarations;
import org.cyclonedx.model.attestation.Assessor;
import org.cyclonedx.model.attestation.Attestation;
import org.cyclonedx.model.attestation.AttestationMap;
import org.cyclonedx.model.attestation.Claim;
import org.cyclonedx.model.attestation.affirmation.Affirmation;
import org.cyclonedx.model.attestation.affirmation.Signatory;
import org.cyclonedx.model.attestation.evidence.Contents;
import org.cyclonedx.model.attestation.evidence.Data;
import org.cyclonedx.model.attestation.evidence.Evidence;
import org.cyclonedx.model.attestation.Targets;
import org.cyclonedx.parsers.JsonParser;
import org.cyclonedx.parsers.XmlParser;
import org.cyclonedx.Version;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.LinkedList;
import java.util.UUID;

/**
 * Command line tool to construct a CycloneDX CDXA.
 */
public final class TemurinGenCDXA {

    private static boolean verbose = false;
    private static boolean useJson = false;

    // Constants for evidence fields
    private static final String EVIDENCE_PROPERTY_NAME = "VERIFICATION_LOG";
    private static final String EVIDENCE_DATA_NAME = "log";
    private static final String EVIDENCE_CONTENT_TYPE = "text/plain";

    // Constants for component properties
    private static final String COMPONENT_IMAGE_TYPE = "jdk";
    private static final String COMPONENT_JVM_IMPL = "hotspot";

    // Valid predicates
    enum CDXAPredicate {
                           VERIFIED_REPRODUCIBLE_BUILD
                       };

    private TemurinGenCDXA() {
    }

    /**
     * Main entry.
     * @param args Arguments for operation.
     */
    public static void main(final String[] args) {
        String cmd = "";
        String attestingOrgName = null;
        String predicate = null;
        String targetRelease = null;
        String targetOs = null;
        String targetArch = null;
        String verifiedJdkFile = null;
        String affirmationStmt = null;
        String affirmationWebsite = null;
        String evidenceText = null;
        String cdxaOutputFolder = "."; // Default to current directory
        boolean thirdParty = true;
        useJson = false; // Default to XML

        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--json")) {
                useJson = true;
            } else if (args[i].equals("--xml")) {
                useJson = false;
            } else if (args[i].equals("--attesting-org-name")) {
                attestingOrgName = args[++i].trim();
            } else if (args[i].equals("--predicate")) {
                predicate = args[++i].trim();
            } else if (args[i].equals("--target-release")) {
                targetRelease = args[++i].trim();
            } else if (args[i].equals("--target-os")) {
                targetOs = args[++i].trim();
            } else if (args[i].equals("--target-arch")) {
                targetArch = args[++i].trim();
            } else if (args[i].equals("--verified-jdk-file")) {
                verifiedJdkFile = args[++i].trim();
            } else if (args[i].equals("--affirmation-stmt")) {
                affirmationStmt = args[++i].trim();
            } else if (args[i].equals("--evidence")) {
                evidenceText = args[++i].trim();
            } else if (args[i].equals("--cdxa-output-folder")) {
                cdxaOutputFolder = args[++i].trim();
            //} else if (args[i].equals("--affirmation-website")) {
            //    affirmationWebsite = args[++i].trim();
            } else if (args[i].equals("--not-third-party")) {
                thirdParty = false;
            } else if (args[i].equals("--createNewCDXA")) {
                cmd = "createCDXA";
            } else if (args[i].equals("--verbose")) {
                verbose = true;
            }
        }

        try {
          switch (cmd) {
            case "createCDXA":  // Create a new CDXA json/xml file
                // Validate output folder
                File outputFolder = new File(cdxaOutputFolder);
                if (!outputFolder.exists()) {
                    System.out.println("ERROR: --cdxa-output-folder '" + cdxaOutputFolder + "' does not exist");
                    System.exit(1);
                }
                if (!outputFolder.isDirectory()) {
                    System.out.println("ERROR: --cdxa-output-folder '" + cdxaOutputFolder + "' is not a directory");
                    System.exit(1);
                }
                if (!outputFolder.canWrite()) {
                    System.out.println("ERROR: --cdxa-output-folder '" + cdxaOutputFolder + "' is not writable");
                    System.exit(1);
                }

                Bom bom = createCdxa(attestingOrgName, predicate, targetRelease, targetOs, targetArch, verifiedJdkFile, affirmationStmt, affirmationWebsite, evidenceText, thirdParty);
                if (bom != null) {
                    // Derive fileName from new parameters
                    String fileName = deriveFileName(targetRelease, targetArch, targetOs, attestingOrgName);
                    // Prepend output folder to filename
                    String fullPath = cdxaOutputFolder + File.separator + fileName;
                    writeFile(bom, fullPath);
                    if (verbose) {
                        System.out.println("CDXA file written to: " + fullPath);
                    }
                } else {
                    System.exit(1);
                }
                break;

            default:
                // Echo input command:
                for (int i = 0; i < args.length; i++) {
                    System.out.print(args[i] + " ");
                }
                System.out.println("\nERROR: Please enter a valid command.");
                System.exit(1);
          }
        } catch (Exception e) {
            // Echo input command:
            for (int i = 0; i < args.length; i++) {
                System.out.print(args[i] + " ");
            }
            System.out.println("\nERROR: Exception: " + e);
            System.exit(1);
        }
    }

    static Bom createCdxa(final String attestingOrgName, final String predicate,
                          final String targetRelease, final String targetOs, final String targetArch,
                          final String verifiedJdkFile, final String affirmationStmt, final String affirmationWebsite,
                          final String evidenceText, final boolean thirdParty) {
        // Validate all inputs
        if (!validateCdxaInputs(attestingOrgName, predicate, targetRelease, targetOs, targetArch,
                                verifiedJdkFile, affirmationStmt, evidenceText)) {
            printUsage();
            return null;
        }

        // Compute SHA-256 hash from the verified JDK file
        String targetHash = computeTargetHash(verifiedJdkFile);
        if (targetHash == null) {
            return null;
        }

        // Derive CDXA values from parameters
        String targetName = deriveTargetName(targetRelease, targetArch, targetOs);
        String targetVersion = targetRelease;
        String targetUrl = deriveTargetUrl(targetRelease, targetOs, targetArch);

        // Create BOM reference IDs
        final String targetJdkBomRef  = "target-jdk-1";
        final String assessorBomRef   = "assessor-1";
        final String claimBomRef      = "claim-1";
        final String evidenceBomRef   = "evidence-1";

        // Build CDXA components
        Declarations declarations = new Declarations();
        Component targetJDK = createTargetComponent(targetName, targetVersion, targetUrl, targetHash,
                                                     targetJdkBomRef, targetArch, targetOs);
        Targets targets = new Targets();
        List<Component> components = new LinkedList<Component>();
        components.add(targetJDK);
        targets.setComponents(components);
        declarations.setTargets(targets);

        Assessor assessor = createAssessor(attestingOrgName, assessorBomRef, thirdParty);
        List<Assessor> assessors = new LinkedList<Assessor>();
        assessors.add(assessor);
        declarations.setAssessors(assessors);

        Claim claim = createClaim(predicate, targetJDK.getBomRef(), claimBomRef, evidenceBomRef);
        List<Claim> claims = new LinkedList<Claim>();
        claims.add(claim);
        declarations.setClaims(claims);

        Affirmation affirmation = new Affirmation();
        affirmation.setStatement(affirmationStmt);
        declarations.setAffirmation(affirmation);

        Evidence evidence = createEvidence(evidenceText, evidenceBomRef);
        List<Evidence> evidenceList = new LinkedList<Evidence>();
        evidenceList.add(evidence);
        declarations.setEvidence(evidenceList);

        Attestation attestation = createAttestation(assessor.getBomRef(), claim.getBomRef());
        List<Attestation> attestations = new LinkedList<Attestation>();
        attestations.add(attestation);
        declarations.setAttestations(attestations);

        // Create CDXA Bom
        Bom cdxa = new Bom();
        cdxa.setSerialNumber("urn:uuid:" + UUID.randomUUID());
        cdxa.setDeclarations(declarations);

        return cdxa;
    }

    /**
     * Validates all CDXA input parameters.
     */
    private static boolean validateCdxaInputs(final String attestingOrgName, final String predicate,
                                              final String targetRelease, final String targetOs,
                                              final String targetArch, final String verifiedJdkFile,
                                              final String affirmationStmt, final String evidenceText) {
        boolean validInput = true;

        if (attestingOrgName == null) {
            System.out.println("ERROR: --attesting-org-name not specified");
            validInput = false;
        }
        if (predicate == null) {
            System.out.println("ERROR: --predicate not specified");
            validInput = false;
        } else {
            boolean validPred = false;
            for (CDXAPredicate validPredicate : CDXAPredicate.values()) {
                if (validPredicate.name().equals(predicate)) {
                    validPred = true;
                    break;
                }
            }
            if (!validPred) {
                System.out.println("ERROR: --predicate " + predicate + " not a valid value");
                validInput = false;
            }
        }
        if (targetRelease == null) {
            System.out.println("ERROR: --target-release not specified");
            validInput = false;
        }
        if (targetOs == null) {
            System.out.println("ERROR: --target-os not specified");
            validInput = false;
        }
        if (targetArch == null) {
            System.out.println("ERROR: --target-arch not specified");
            validInput = false;
        }
        if (verifiedJdkFile == null) {
            System.out.println("ERROR: --verified-jdk-file not specified");
            validInput = false;
        } else {
            File jdkFile = new File(verifiedJdkFile);
            if (!jdkFile.exists()) {
                System.out.println("ERROR: --verified-jdk-file '" + verifiedJdkFile + "' does not exist");
                validInput = false;
            } else if (!jdkFile.isFile()) {
                System.out.println("ERROR: --verified-jdk-file '" + verifiedJdkFile + "' is not a file");
                validInput = false;
            } else if (!jdkFile.canRead()) {
                System.out.println("ERROR: --verified-jdk-file '" + verifiedJdkFile + "' is not readable");
                validInput = false;
            }
        }
        if (affirmationStmt == null) {
            System.out.println("ERROR: --affirmation-stmt not specified");
            validInput = false;
        }
        if (evidenceText == null) {
            System.out.println("ERROR: --evidence not specified");
            validInput = false;
        } else if (evidenceText.trim().isEmpty()) {
            System.out.println("ERROR: --evidence cannot be empty");
            validInput = false;
        }

        // Perform extra validation steps on values to ensure meets Temurin CDXA format syntax
        if (validInput) {
            validInput = validateInputParameters(targetRelease, targetOs, targetArch, attestingOrgName);
        }

        return validInput;
    }

    /**
     * Computes SHA-256 hash from the verified JDK file.
     */
    private static String computeTargetHash(final String verifiedJdkFile) {
        try {
            String targetHash = computeSHA256(verifiedJdkFile);
            if (verbose) {
                System.out.println("Computed SHA-256: " + targetHash);
            }
            return targetHash;
        } catch (IOException | NoSuchAlgorithmException e) {
            System.out.println("ERROR: Failed to compute SHA-256 hash from file '"
                             + verifiedJdkFile + "': " + e.getMessage());
            return null;
        }
    }

    /**
     * Creates the target JDK component with all properties.
     */
    private static Component createTargetComponent(final String targetName, final String targetVersion,
                                                   final String targetUrl, final String targetHash,
                                                   final String bomRef, final String targetArch,
                                                   final String targetOs) {
        // External reference to the target JDK
        ExternalReference extRef = new ExternalReference();
        Hash hash1 = new Hash(Hash.Algorithm.SHA_256, targetHash);
        extRef.addHash(hash1);
        extRef.setUrl(targetUrl);
        extRef.setType(ExternalReference.Type.DISTRIBUTION);

        // Target JDK Component
        Component targetJDK = new Component();
        targetJDK.setType(Component.Type.APPLICATION);
        targetJDK.setName(targetName);
        targetJDK.setVersion(targetVersion);
        targetJDK.addExternalReference(extRef);
        targetJDK.setBomRef(bomRef);

        // Property for "platform" = {arch}_{os}
        Property property = new Property();
        property.setName("platform");
        property.setValue(targetArch + "_" + targetOs);
        targetJDK.addProperty(property);

        // Property for "imageType"
        Property imageTypeProperty = new Property();
        imageTypeProperty.setName("imageType");
        imageTypeProperty.setValue(COMPONENT_IMAGE_TYPE);
        targetJDK.addProperty(imageTypeProperty);

        // Property for "jvmImpl"
        Property jvmImplProperty = new Property();
        jvmImplProperty.setName("jvmImpl");
        jvmImplProperty.setValue(COMPONENT_JVM_IMPL);
        targetJDK.addProperty(jvmImplProperty);

        return targetJDK;
    }

    /**
     * Creates the assessor component.
     */
    private static Assessor createAssessor(final String attestingOrgName, final String bomRef,
                                          final boolean thirdParty) {
        Assessor assessor = new Assessor();
        assessor.setThirdParty(thirdParty);
        OrganizationalEntity org = new OrganizationalEntity();
        org.setName(attestingOrgName);
        assessor.setOrganization(org);
        assessor.setBomRef(bomRef);
        return assessor;
    }

    /**
     * Creates the claim component.
     */
    private static Claim createClaim(final String predicate, final String targetBomRef,
                                    final String claimBomRef, final String evidenceBomRef) {
        Claim claim = new Claim();
        claim.setPredicate(predicate);
        claim.setTarget(targetBomRef);
        claim.setBomRef(claimBomRef);

        // Add evidence reference to claim
        List<String> evidenceRefs = new LinkedList<String>();
        evidenceRefs.add(evidenceBomRef);
        claim.setEvidence(evidenceRefs);

        return claim;
    }

    /**
     * Creates the evidence component.
     */
    private static Evidence createEvidence(final String evidenceText, final String bomRef) {
        Evidence evidence = new Evidence();
        evidence.setBomRef(bomRef);
        evidence.setPropertyName(EVIDENCE_PROPERTY_NAME);

        // Create Data object
        Data data = new Data();
        data.setName(EVIDENCE_DATA_NAME);

        // Create Contents with AttachmentText
        Contents contents = new Contents();
        AttachmentText attachment = new AttachmentText();
        attachment.setContentType(EVIDENCE_CONTENT_TYPE);
        attachment.setText(evidenceText);
        contents.setAttachment(attachment);
        data.setContents(contents);

        // Add data to evidence
        List<Data> dataList = new LinkedList<Data>();
        dataList.add(data);
        evidence.setData(dataList);

        return evidence;
    }

    /**
     * Creates the attestation component.
     */
    private static Attestation createAttestation(final String assessorBomRef, final String claimBomRef) {
        Attestation attestation = new Attestation();
        attestation.setSummary("Eclipse Temurin CycloneDX Attestation");
        attestation.setAssessor(assessorBomRef);

        AttestationMap attestationMap = new AttestationMap();
        List<String> claimsList = new LinkedList<String>();
        claimsList.add(claimBomRef);
        attestationMap.setClaims(claimsList);

        List<AttestationMap> attestationMaps = new LinkedList<AttestationMap>();
        attestationMaps.add(attestationMap);
        attestation.setMap(attestationMaps);

        return attestation;
    }

    /**
     * Prints usage information for the command-line tool.
     */
    static void printUsage() {
        System.out.println("\nUsage: TemurinGenCDXA --createNewCDXA [OPTIONS]");
        System.out.println("\nRequired Options:");
        System.out.println("  --attesting-org-name <name>    Organization name making the attestation");
        System.out.println("  --predicate <predicate>        Predicate type (e.g., VERIFIED_REPRODUCIBLE_BUILD)");
        System.out.println("  --target-release <release>     JDK release (format: jdk-M+B or jdk-M.0.U+B)");
        System.out.println("  --target-os <os>               Target OS (linux, windows, mac)");
        System.out.println("  --target-arch <arch>           Target architecture (x64, aarch64, s390x, ppc64le)");
        System.out.println("  --verified-jdk-file <path>     Path to JDK tar.gz or zip file (SHA-256 will be computed)");
        System.out.println("  --affirmation-stmt <stmt>      Affirmation statement");
        System.out.println("  --evidence <text>              Verification log text (e.g., reproducible build comparison output)");
        System.out.println("\nOptional Options:");
        System.out.println("  --cdxa-output-folder <path>    Output folder for CDXA file (default: current directory)");
        //System.out.println("  --affirmation-website <url>    Organization website");
        System.out.println("  --json                         Generate JSON output (default: XML)");
        System.out.println("  --xml                          Generate XML output");
        System.out.println("  --not-third-party              Mark assessor as not third-party");
        System.out.println("  --verbose                      Enable verbose output");
        System.out.println("\nExamples:");
        System.out.println("  TemurinGenCDXA --createNewCDXA --target-release jdk-21.0.1+12 \\");
        System.out.println("    --target-os linux --target-arch x64 \\");
        System.out.println("    --attesting-org-name \"Acme Inc\" \\");
        System.out.println("    --predicate VERIFIED_REPRODUCIBLE_BUILD \\");
        System.out.println("    --verified-jdk-file /path/to/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz \\");
        System.out.println("    --affirmation-stmt \"Build verified as reproducible\" \\");
        System.out.println("    --evidence \"Comparing expanded JDKs...Compare identical!\" \\");
        System.out.println("    --cdxa-output-folder /output/cdxa \\");
        //System.out.println("    --affirmation-website \"https://acme.inc.com\"");
        System.out.println("    --xml");
        System.out.println("\nOutput:");
        System.out.println("  Generated filename format: {release}_{arch}_{os}_{org}.{xml|json}");
        System.out.println("  Example: jdk_21_0_1_12_x64_linux_eclipse.xml");
        System.out.println("\nNote: SHA-256 hash will be automatically computed from the verified-jdk-file");
    }

    /**
     * Validates input parameters according to Temurin CDXA requirements.
     *
     * @param targetRelease The target release (jdk-M+B or jdk-M.0.U+B format)
     * @param targetOs The target OS (linux, windows, mac)
     * @param targetArch The target architecture (x64, aarch64, s390x, ppc64le)
     * @param attestingOrgName The attesting organization name
     * @return true if valid, false otherwise
     */
    static boolean validateInputParameters(final String targetRelease, final String targetOs,
                                           final String targetArch, final String attestingOrgName) {
        boolean valid = true;

        // Validate targetRelease format: jdk-M+B or jdk-M.0.U+B
        Pattern releasePattern = Pattern.compile("^jdk-([0-9]+)(\\.[0-9]+\\.[0-9]+)?\\+([0-9]+)$");
        Matcher releaseMatcher = releasePattern.matcher(targetRelease);
        if (!releaseMatcher.matches()) {
            System.out.println("ERROR: --target-release '" + targetRelease + "' is not in valid format: jdk-M+B or jdk-M.0.U+B");
            valid = false;
        }

        // Validate targetOs
        if (!targetOs.equals("linux") && !targetOs.equals("windows") && !targetOs.equals("mac")) {
            System.out.println("ERROR: --target-os '" + targetOs + "' must be one of: linux, windows, mac");
            valid = false;
        }

        // Validate targetArch
        if (!targetArch.equals("x64") && !targetArch.equals("aarch64")
            && !targetArch.equals("s390x") && !targetArch.equals("ppc64le")) {
            System.out.println("ERROR: --target-arch '" + targetArch + "' must be one of: x64, aarch64, s390x, ppc64le");
            valid = false;
        }

        // Validate attestingOrgName is not empty
        if (attestingOrgName.trim().isEmpty()) {
            System.out.println("ERROR: --attesting-org-name cannot be empty");
            valid = false;
        }

        return valid;
    }

    /**
     * Derives the target name from release, arch, and OS.
     * Format: "Temurin {targetRelease} {targetArch}_{targetOs}"
     *
     * @param targetRelease The target release
     * @param targetArch The target architecture
     * @param targetOs The target OS
     * @return The derived target name
     */
    static String deriveTargetName(final String targetRelease, final String targetArch, final String targetOs) {
        return "Temurin " + targetRelease + " " + targetArch + "_" + targetOs;
    }

    /**
     * Derives the target URL from release, OS, and arch.
     * Format: "https://api.adoptium.net/v3/binary/version/{targetRelease}/{targetOs}/{targetArch}/jdk/hotspot/normal/eclipse"
     *
     * @param targetRelease The target release
     * @param targetOs The target OS
     * @param targetArch The target architecture
     * @return The derived target URL
     */
    static String deriveTargetUrl(final String targetRelease, final String targetOs, final String targetArch) {
        return "https://api.adoptium.net/v3/binary/version/" + targetRelease + "/" + targetOs + "/" + targetArch + "/jdk/hotspot/normal/eclipse";
    }

    /**
     * Derives the file name from release, arch, OS, and attesting org.
     * Format: "{targetRelease with [-\.\+] converted to [_]}_{targetArch}_{targetOs}_{attestingOrgName}.{xml|json}"
     *
     * @param targetRelease The target release
     * @param targetArch The target architecture
     * @param targetOs The target OS
     * @param attestingOrgName The attesting organization name
     * @return The derived file name
     */
    static String deriveFileName(final String targetRelease, final String targetArch,
                                 final String targetOs, final String attestingOrgName) {
        // Convert all [-\.\+] to [_] in targetRelease
        String releaseFormatted = targetRelease.replaceAll("[-\\.\\+]", "_");
        // Remove all non-alphanumeric characters from attestingOrgName for valid filename
        String orgFormatted = attestingOrgName.replaceAll("[^a-zA-Z0-9]", "");
        String extension = useJson ? "json" : "xml";
        return releaseFormatted + "_" + targetArch + "_" + targetOs + "_" + orgFormatted + "." + extension;
    }

    static String generateBomJson(final Bom bom) throws GeneratorException {
        // Use schema v16: https://cyclonedx.org/schema/bom-1.6.schema.json
        BomJsonGenerator bomGen = new BomJsonGenerator(bom, Version.VERSION_16);
        String json = bomGen.toJsonString();
        return json;
    }

    static String generateBomXml(final Bom bom) throws GeneratorException {
        BomXmlGenerator bomGen = new BomXmlGenerator(bom, Version.VERSION_16);
        String xml = bomGen.toXmlString();
        return xml;
    }

    // Writes the BOM object to the specified type of file
    static void writeFile(final Bom bom, final String fileName) {
        if (useJson) {
            writeJSONfile(bom, fileName);
        } else {
            writeXMLfile(bom, fileName);
        }
    }

    // Writes the BOM object to the specified JSON file.
    static void writeJSONfile(final Bom bom, final String fileName) {
        FileWriter file;
        try {
            String json = generateBomJson(bom);

            file = new FileWriter(fileName);
            file.write(json);
            file.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    // Writes the BOM object to the specified XML file.
    static void writeXMLfile(final Bom bom, final String fileName) {
        FileWriter file;
        try {
            String xml = generateBomXml(bom);

            file = new FileWriter(fileName);
            file.write(xml);
            file.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    // Returns a parsed BOM object from the specified file.
    static Bom readJSONfile(final String fileName) {
        Bom bom = null;
        try {
            FileReader reader = new FileReader(fileName);
            JsonParser parser = new JsonParser();
            bom = parser.parse(reader);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        } finally {
           return bom;
        }
    }

    // Returns a parsed BOM object from the specified file.
    static Bom readXMLfile(final String fileName) {
        Bom bom = null;
        try {
            FileReader reader = new FileReader(fileName);
            XmlParser parser = new XmlParser();
            bom = parser.parse(reader);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        } finally {
           return bom;
        }
    }

    /**
     * Computes the SHA-256 hash of a file.
     *
     * @param filePath The path to the file
     * @return The SHA-256 hash as a hexadecimal string
     * @throws IOException If an I/O error occurs
     * @throws NoSuchAlgorithmException If SHA-256 algorithm is not available
     */
    static String computeSHA256(final String filePath) throws IOException, NoSuchAlgorithmException {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");

        try (FileInputStream fis = new FileInputStream(filePath)) {
            byte[] buffer = new byte[8192];
            int bytesRead;

            while ((bytesRead = fis.read(buffer)) != -1) {
                digest.update(buffer, 0, bytesRead);
            }
        }

        byte[] hashBytes = digest.digest();

        // Convert byte array to hexadecimal string
        StringBuilder hexString = new StringBuilder();
        for (byte b : hashBytes) {
            String hex = Integer.toHexString(0xff & b);
            if (hex.length() == 1) {
                hexString.append('0');
            }
            hexString.append(hex);
        }

        return hexString.toString();
    }
}
