name: Fetch and Upload Temurin SBOMs to DependencyTrack

on:
  workflow_dispatch:

env:
  API_URL_BASE: https://api.adoptium.net/v3/assets/feature_releases/21/ga
  IMAGE_TYPE: sbom
  VENDOR: eclipse
  HEAP_SIZE: normal
  PAGE_SIZE: 20
  DEPENDENCY_TRACK_URL: https://sbom.eclipse.org
  PROJECT_ROOT: Temurin
  JAVA_VERSION: JDK 21

jobs:
  fetch-sboms:
    runs-on: ubuntu-latest

    outputs:
      sbom-metadata: ${{ steps.export.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install requests

      - name: Run SBOM fetcher script
        run: python fetch_sboms.py

      - name: Upload SBOMs and metadata
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            sboms/
            metadata.json

      - id: export
        run: |
          matrix=$(jq -c '.' metadata.json)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  store-each-sbom:
    needs: fetch-sboms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: ${{ fromJson(needs.fetch-sboms.outputs.sbom-metadata) }}

    steps:
      - name: Download SBOMs
        uses: actions/download-artifact@v4
        with:
          name: sboms
          path: workspace

      - name: Store SBOM in DependencyTrack
        uses: eclipse-csi/workflows/.github/workflows/store-sbom-data.yml@main
        with:
          projectName: ${{ matrix.projectName }}
          projectVersion: ${{ matrix.projectVersion }}
          bomArtifact: sboms
          bomFilename: workspace/${{ matrix.path }}
          parentProject: '<parentProject_ID>' # must replace with real UUID
